name: 'Create Request'
description: 'Creates a Request (Normal or Standard).'
outputs:
  command: 
    description: "INPUT_DESCRIPTION"
    value: ${{ steps.cr.outputs.command }}
  http_code: 
    description: "INPUT_DESCRIPTION"
    value: ${{ steps.cr.outputs.http_code }}
  number: 
    description: "INPUT_DESCRIPTION"
    value: ${{ steps.cr.outputs.number }}
runs:
  using: "composite"
  steps:
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action/@main
      with:
        version: "v2.0.2"
    - shell: bash
      id: cr
      run: |
        #!/bin/bash
        ENDPOINT=https://jsonplaceholder.typicode.com/posts
        AUTH_HEADER=abc:123                        
        INPUT_SHORT_DESCRIPTION=test
        INPUT_DESCRIPTION="\"\ttest \"ali\"\n"
        INPUT_ASSIGNMENT_GROUP=test
        INPUT_REQUESTED_BY=test
        TEST_PLAN='1. Who is going to perform technical validation? (Provide name and contact #): xmatters Azure_Support\n2. When will the technical validation occur? Start date and time: Day of or after release\n3. When will the functionality be turned on (toggle on) to the users? Immediately preceding release\n4. Who is going to perform business/end user validation? (Provide name and contact #): Application teams\n5. When will the end-user validation occur? Start date and time: Next business day'
        CURL_CMD=$(cat <<EOF
        curl -s -w "%{http_code}" -o response.json \
          -X POST "$ENDPOINT" \
          -H "Content-Type: application/json" \
          -d '{ \
            "title": "foo",\
            "body": "$TEST_PLAN", \
              "result": [ \
              { \
              "number": "CHG110022" \
              }], \
            "userId": 1 \
        }'
        EOF
        )
        RES=$(eval "$CURL_CMD")
        HTTP_CODE=$(tail -c 4 <<< "$RES")
        echo $HTTP_CODE
        echo =================================
        cat response.json
        echo =================================
        curl --version
        echo "http_code=$HTTP_CODE" >> $GITHUB_OUTPUT
        grep "number" response.json | cut -d '"' -f4 
        grep "number" response.json | cut -d '"' -f4  | xargs -I {} echo "number={}" >> $GITHUB_OUTPUT
        echo "command=$CURL_CMD" >> $GITHUB_OUTPUT





