name: 'Create ServiceNow Change Request'
description: 'Creates a ServiceNow Change Request (Normal or Standard).'
outputs:
  command: 
    description: "INPUT_DESCRIPTION"
    value: ${{ steps.cr.outputs.command }}
  http_code: 
    description: "INPUT_DESCRIPTION"
    value: ${{ steps.cr.outputs.http_code }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: cr
      run: |
        ENDPOINT=https://jsonplaceholder.typicode.com/posts
        AUTH_HEADER=abc:123                        
        INPUT_SHORT_DESCRIPTION=test
        INPUT_DESCRIPTION="\"\ttest \"ali\"\n"
        INPUT_ASSIGNMENT_GROUP=test
        INPUT_REQUESTED_BY=test
        CURL_CMD=$(cat <<EOF
        curl -s -w "%{http_code}" -o response.json \
          -X POST "$ENDPOINT" \
          -H "Content-Type: application/json" \
          -d '{ \
            "title": "foo",\
            "body": "bar", \
            "userId": 1 \
        }'
        EOF
        )
        # RES=$(eval "$CURL_CMD")
        # HTTP_CODE=$(tail -c 4 <<< "$RES")
        # echo $HTTP_CODE
        echo =================================
        cat response.json
        echo =================================
        curl --version
        echo "http_code=$HTTP_CODE" >> $GITHUB_OUTPUT
        # COMMAND=$(echo "$CURL_CMD" | sed '$!s/$/ \\/')
        echo "command=$CURL_CMD" >> $GITHUB_ENV





