name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.JSON_RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        echo 'JSON_RESPONSE<<EOF'
        curl https://example.com
        echo EOF
        echo "JSON_RESPONSE=$JSON_RESPONSE" >> "$GITHUB_OUTPUT"

        