name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.JSON_RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
        echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
        echo "JSON_RESPONSE=$GITHUB_STEP_SUMMARY" >> "$GITHUB_OUTPUT"

        