name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.JSON_RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        # Initialize an empty variable
        OUTPUT=""
        ERROR_LOG=$(cat <<EOF
        Message:               Failed to install after 1 attempt(s)
        Message:               Helm install failed for release default/nginx-helm with chart nginx@13.2.19: context deadline exceeded
        Message:               Helm install failed for release default/nginx-helm with chart nginx@13.2.19: context deadline exceeded
        EOF
        )

        # Loop to generate multiple lines and append to OUTPUT variable
        for i in {1..5}; do
          OUTPUT+="$i $ERROR_LOG\n"  # Append to OUTPUT variable
        done
        OUTPUT="${OUTPUT//'%'/'%25'}"
        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
        echo "JSON_RESPONSE=$OUTPUT" >> $GITHUB_OUTPUT

        