name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.JSON_RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        # Initialize an empty variable
        OUTPUT=""

        # Loop to generate multiple lines
        for i in {1..5}; do
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_OUTPUT
          echo "hello $i" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        done

