name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.ENCODED_OUTPUT }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        # Initialize an empty variable
        OUTPUT=""

        # Loop to generate multiple lines
        for i in {1..5}; do
          echo "Hello\n"
          echo $(echo "Line $i")$'\n'
          echo "=======Bye======="
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_OUTPUT
          echo "Hello\n" >> $GITHUB_OUTPUT
          echo $(echo "Line $i")$'\n' >> $GITHUB_OUTPUT
          echo "=======Bye=======" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        done

