name: "Loop Output Action"
description: "Runs a Bash loop, encodes output, and exports it"

outputs: 
  ENCODED_OUTPUT:
    description: none
    value: ${{ steps.cr.outputs.JSON_RESPONSE }}
  SAMPLE_OUTPUT:
    description: none
    value: ${{ steps.br.outputs.JSON_RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Run Bash Loop and Encode Output
      shell: bash
      id: cr
      run: |
        TMPFILE=cr-tmpfile
        > $TMPFILE
        echo "This is the lead in sentence for the list" >> $TMPFILE
        echo "" >> $TMPFILE # this is a blank line
        echo "- Lets add a bullet point" >> $TMPFILE
        echo "- Lets add a second bullet point" >> $TMPFILE
        echo "- How about a third one?" >> $TMPFILE
        echo "JSON_RESPONSE=$(pwd)/$TMPFILE" >> "$GITHUB_OUTPUT"

    - name: Run Bash Loop and Encode Output
      shell: bash
      id: br
      run: |
        TMPFILE=br-tmpfile
        > $TMPFILE
        echo "This is the lead in sentence for the list" >> $TMPFILE
        echo "" >> $TMPFILE # this is a blank line
        echo "1 Lets add a bullet point" >> $TMPFILE
        echo "2 Lets add a second bullet point" >> $TMPFILE
        echo "3 How about a third one?" >> $TMPFILE
        echo "JSON_RESPONSE=$(pwd)/$TMPFILE" >> "$GITHUB_OUTPUT"
        