name: Create Request

on:
  push:

jobs:
  create_request:
    runs-on: ubuntu-latest
    steps:
    - name: New CR
      id: cr
      uses: dev-sha-ops/azure-agw-key-vault-self-signed-tls/.github/actions/br@main
    - name: New out
      shell: bash
      run: |
        #!/bin/bash
        echo -n ${{ steps.cr.outputs.ENCODED_OUTPUT }} || true 
        echo ====================================
        echo -e ${{ steps.cr.outputs.ENCODED_OUTPUT }} || true 

