name: Create Request

on:
  push:

jobs:
  create_request:
    runs-on: ubuntu-latest
    steps:
    - name: New CR
      id: cr
      uses: dev-sha-ops/azure-agw-key-vault-self-signed-tls/.github/actions/cr@main
    - name: New out
      run: |
        echo ${{ steps.cr.outputs.command }}
        echo ++==============================++
        echo ${{ steps.cr.outputs.http_code }}


