name: Create Request

on:
  push:

jobs:
  create_request:
    runs-on: ubuntu-latest
    steps:
    - name: New CR
      id: cr
      uses: dev-sha-ops/azure-agw-key-vault-self-signed-tls/.github/actions/br@main
    - name: New CR out
      run: |
        cat ${{ steps.cr.outputs.ENCODED_OUTPUT}}

    - name: New BR out
      if: always()
      run: |
        while IFS= read -r line; do
            echo "$line"
        done < ${{ steps.cr.outputs.SAMPLE_OUTPUT }}

    - name: Cleanup
      shell: bash
      if: always()
      run: |
        set -e
        rm -f ${{ steps.cr.outputs.SAMPLE_OUTPUT }} ${{ steps.cr.outputs.ENCODED_OUTPUT }}